rails_version: 4.2.9
versions:
  master:
    github: RailsEventStore/rails_event_store
    branch: master
  withLocking:
    github: RailsEventStore/rails_event_store
    branch: locking_friendly
  v0.15: ~> 0.15.0
  v0.14: ~> 0.14.0
  v0.13: ~> 0.13.0
  v0.12: ~> 0.12.0
  v0.11: ~> 0.11.0
  v0.10: ~> 0.10.0
  v0.09: ~> 0.9.0
